# Generated by Django 5.2.6 on 2025-10-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_n', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content_n', models.TextField(verbose_name='Содержание')),
            ],
        ),
    ]
